name: Testando o que isso

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    env:
      var_2: ${{ secrets.PEDRO_REPO }}
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: actions/checkout@v2
      - name: meu echo
        run: python -c "input()"
      - name: Rodando script shell
        run: ./run.sh

      - name: Criando arquivo
        run: |
          echo "$var" > file.txt
          cat file.txt
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .


