name: Testando o que isso

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - name: meu echo
        env:
          var: ${{ secrets.PEDRO_ORG }}
          var_2: ${{ secrets.PEDRO_REPO }}
        run: |
          ls
          echo teste1
          ls -la
      - name: Rodando script shell
        run: ./run.sh

      - name: Criando arquivo
        run: |
          echo 'Um texto' > file.txt
          cat file.txt
