name: Testando o que isso

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    name: Um job que constrói uma imagem Docker
    env:
      my_secret: ${{ secrets.TESTE_DE_UM_SECRET }}
    steps:
      - name: Cópia o repositório (checkout para o commit atual)
        uses: actions/checkout@v2

#      - name: Docker create
#        run: |
#          docker build --tag pedroregispoar/teste-ci .
#          docker run --env MY_VAR="$my_secret" pedroregispoar/teste-ci sh -c 'cat out.log && echo $MY_VAR'

      - name:
        run: |
#          echo env_variable_name=${{ secrets.CI_SECRET_KEY }} > file.txt
#          cat file.txt
          ./run.sh
          cat file.txt

#      - name: Executa o ./main "$1" "$2" "$3"
#        run: |
#          ./main.sh registry app 0.0.1
#          cat .env.ci
#
#      - name: Executa usa a imagem construída
#        run: docker run registry/app:0.0.1 sh -c 'cat .env'


#      - name: Rodando script shell
#        run: ./run.sh
#
#      - name: Criando arquivo
#        run: |
#          echo "$var" > file.txt
#          cat file.txt
#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: .
#

