name: Testando o que isso

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: meu echo
        env:
          var: value
          var_2: value_2
        run: echo "$var" "$var_2"

