name: Testando o que isso

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: meu echo
        env:
          var: ${{ secrets.PEDRO_ORG }}
          var_2: ${{ secrets.PEDRO_REPO }}
        run: |
          ls
          echo teste1
          ls -la

